# Generated by Django 5.0.3 on 2024-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='hour',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monitor',
            name='minute',
            field=models.IntegerField(default=30),
        ),
    ]
